name: list_benchmark
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0-29.7.beta <3.0.0'

dependencies:
  benchmark_harness: ^2.0.0
  path: ^1.7.0

dev_dependencies:
  extra_pedantic: ^1.3.0
